[profile.default]
src = "contracts/src"
test = "contracts/test"
script = "contracts/script"
out = ".artifacts/contracts"
cache_path = ".cache/forge"
libs = ["node_modules"]
remappings = ["@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"]
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.default.fuzz]
runs = 512

[profile.default.invariant]
runs = 128
depth = 32
